### ISSUE TITLE
WPAndroid: implement onboarding experience

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#271]
See #265

**Comment by megsfulton** [comment]
Assets for the intro to stories screen: 
[demostorycovers.zip](https://github.com/Automattic/stories-android/files/5367670/demostorycovers.zip)

Demo 1: https://wpstories.wordpress.com/2020/10/12/patagonia-2/

Demo 2: https://wpstories.wordpress.com/2020/10/12/hiking-in-the-southwest/

Both the cover and story links are placeholder until closer to launch. When implemented they should be easy to swap out and update before the production release.
