### ISSUE TITLE
Story Page editing changes: drag to remove page

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#294]
Originally in #277 

<img width="512" alt="opt-1-drag-to-delete-frame" src="https://user-images.githubusercontent.com/6597771/76644944-bf479400-6536-11ea-8f88-85b57176a728.png">

The idea behind this is that you can either drag text/emoji OR even pages from the bottom strip out of it and drop it on the trash icon to delete a full page from your current Story. This implies rolling out our own drag and drop handling. It can be done but it's laborious and will need a very custom implementation, hence tracking here for later.

**Comment by aforcier** [comment]
No longer needed, as of #562 the behavior is to tap the active slide and then tap the delete button to delete it.
