### ISSUE TITLE
Unexpectedly triggering delete/trash button when text is angled

### ISSUE THREAD

**Issue by megsfulton** [Automattic/stories-android#394]
Steps:
1) Add text to story
2) Angle the text
3) Drag it around the screen
4) The delete button gets triggered unexpectedly 

Video: https://cloudup.com/cBtWf0bCr8W

Expected:
The delete button would only be triggered when the object is closer / visibly in contact with the delete button. 

Update: We decided to resolve this by showing the delete button on long press instead, so deleting isn't possible while simply moving the view around.

**Comment by aforcier** [comment]
I had a thought about this - Canvas only triggers the trash button for individual elements when long pressing. This means that the trash action isn't available while moving a view around. Maybe we should do the same? What do you think @megsfulton ?

**Comment by megsfulton** [comment]
Oh interesting. Tried it out on my iPhone and works pretty well. Let's go ahead and do that.

**Comment by aforcier** [comment]
> Oh interesting. Tried it out on my iPhone and works pretty well. Let's go ahead and do that.

Great! @mzorz I'll add this to our 'hack week' group of issues then.

**Comment by mzorz** [comment]
This may be improved substantially by this here https://github.com/Automattic/stories-android/pull/512 (was intending to fix some other thing but making enhancements to the detection algorithm also seems to alleviate  / address the situation described in this issue). That said, I think we should still go ahead and implement the [suggestion by Alex](https://github.com/Automattic/stories-android/issues/394#issuecomment-683188067) and totally nail the "deletion issues" for good 🤞
