### ISSUE TITLE
Not Stories Project: Media library Feedback - easy to trigger video playing when selecting a video

### ISSUE THREAD

**Issue by megsfulton** [Automattic/stories-android#398]
What happens:
1) Open media picker, select multiple pieces of media
2) Tap on the center of the video media and it opens a fullscreen video playback mode

What I'd expect: 
I don't expect to trigger the video playback when selecting the video media. I'd expect to trigger the fullscreen playback on a long press which is how to preview photo media.

**Comment by mzorz** [comment]
Moved to https://github.com/wordpress-mobile/WordPress-Android/issues/12853
