### ISSUE TITLE
Remove trash icon from delete slide menu, match style to menu used else where in the app

### ISSUE THREAD

**Issue by megsfulton** [Automattic/stories-android#399]
![Screenshot_20200626-154927](https://user-images.githubusercontent.com/161697/85907322-f67c4100-b7c5-11ea-911f-762661697448.png)

![Screenshot_20200626-155030](https://user-images.githubusercontent.com/161697/85907326-f9773180-b7c5-11ea-9854-38c951e85341.png)

**Comment by aforcier** [comment]
When working on this check that matching WPAndroid's style also resolves the dark mode issue with this element (#443).
