### ISSUE TITLE
Camera FAB icon in media picker confused with  "next step" for media selection

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#424]
> I kept tapping the pink camera FAB after selecting a photo, thinking that it was the action to proceed. The checkmark in the toolbar didn’t feel like it was the obvious way to proceed.

**Comment by mzorz** [comment]
The final decision is to hide the FAB when we have something selected on the grid 👍 

Also, this is in the media picker consolidation project so, if they don't fix it first, we can do it when we reach to it. Reference: https://github.com/wordpress-mobile/WordPress-Android/issues/12644

**Comment by aforcier** [comment]
This was added a while ago in https://github.com/wordpress-mobile/WordPress-Android/pull/12892, looks like we overlooked closing this issue out.
