### ISSUE TITLE
Enhancement: possibility to drag / center / zoom image in slide

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#432]
> One extra thing I forgot to mention – when adding an existing image, the image gets blown up to full screen and only the center of the image is used. It would be nice if you could move it around or resize it somehow to choose which part of the image is used.

Tagging this one as `Needs Design` to discuss with @megsfulton

**Comment by aforcier** [comment]
Pan/zoom has since been added 🎉  (see https://github.com/Automattic/stories-android/issues/646)
