### ISSUE TITLE
Dark theme issues on WPAndroid

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#443]
Tested this myself:

**Enable dark theme**
Go to Settings -> Display -> Dark theme (turn ON)

**Check the media picker when creating  a Story on WPAndroid:**
- white background on thumbnail grid.
- when in Gutenberg, add image, add media -> choose from device. The background appears WHITE as well (bug). If you choose WPMedia the background is dark. Same for Free photo library (works ok). So basically this is a bug in the Media Picker in WPAndroid. (issue on WPAndroid GH repo opened here https://github.com/wordpress-mobile/WordPress-Android/issues/12622)

**In Stories creator**
- font color white on black for inactive (no selection), blue on black when a selection is made -> same for media picker on WPAndroid normally ✅ 
- "Delete slide" option font color white over white (text can't be read)
- NEXT button blue over white, seems fine probably, unless we need to change the white for dark or another color?) cc @megsfulton

**Comment by mzorz** [comment]
Opened issue in WPAndroid repo https://github.com/wordpress-mobile/WordPress-Android/issues/12622

**Comment by mzorz** [comment]
> "Delete slide" option font color white over white (text can't be read)

This is fixed in #507, moving to "Awaiting review"

**Comment by aforcier** [comment]
Note: I anticipate some work to be needed for the color picker bottom sheet once that's done - with this issue closed I added a note to the edit screen primary thread for myself so I don't forget: https://github.com/Automattic/stories-android/issues/274
